dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: kJOsBkZmwL76cVkdy6J/ppTJXxB2pMGGzLw9xOvBPNLvVcDYpHZXhPhe1nGVnbn+tzstQKRJGib08tZlWpzA6if+enwnPGi5HUrUt6dG+20uujrvXt66lH5pGfGRuIBgdZM7os63ESLA3y49OtIbv2IKM7nnstfj4aOa5NLAtkXa255K9os9aTuHMLnxMRDYbONFYvQJa+52z/Tp38vsiV3gjGqZ82fH5SOFFE5mqxDjRFVZNY74aOSeboHmsiRP3k7aQ1+wOFW8iGZFEhNaZhKFisDdAcr7hn/SrvJdD60jPJEqPD5UI3Kga3mRwGLnBERYM87Z2oVkWGR2QBWZKBTxkeVGjHzEtWOHaQ3sQrQLYr8XULTIDHJ3WJSYn4w+djmf7fi0ZVYCJJQtzBIFln/5u2MzLfVuHGPd3V/HEKRnuBUx/7BIH1nyQ7mCc92DsJfrWuMYUnan+FhesrZ5X9YnNvDe8GKxLRvO9bGgt/qRsqb/+gmueZABT8+E25X1D0Hbfp7p9Y19DGwGlWU1sHxMimT58E2zMBuoZyTZcLROtg5UTJsLrYPpcZ3bUj0Bev8PVAEJeSI6GT+MUimXmcSxcS7qoghYPVU0nrk4m/uiI5CIccv1+ZxvdLY10ZlExw+alcFftYYoBdmi3AKNKVESYJVMZEQBsH5SURBfH6k=
