---
- name: Install mongodb
  hosts: all
  become: true
  tasks:
    - name: Add mongodb repo key
      apt_key:
          url: https://www.mongodb.org/static/pgp/server-3.2.asc
          keyring: /etc/apt/trusted.gpg.d/mongodb.gpg
          state: present

    - name: Add mongodb repo
      apt_repository:
          repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
          state: present
          update_cache: yes
          filename: mongodb-org-3.2.list

    - name: Install mongodb
      apt:
        name: mongodb-org
        state: present

    - name: Enable mongodb service
      service:
        name: mongod
        enabled: yes
